name: cypress tests

on: 
  workflow_dispatch:
    inputs:
      cli:
      descriptions: Run by cypress command line
      default: npx cypress run
  
jobs: 
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps: 
    - name: Get code
      uses: actions/checkout@v3.3.0  

    - name: Install dependencies 
      run: ${{ github.event.inputs.cli}}
      
    - name: Run E2E tests
      run: npx cypress run 

   
        
      
